### ISSUE TITLE
Missing step for using ModelCreationInjection

### ISSUE THREAD

**Issue by fjdiazt** [OlegAxenow/EntityFramework.Injection#2]
I had a bit of trouble getting my injection to work, because there is no mention that we have to register the ModelCreationBuilder first using

``` C#
MethodBuilderRegistry.Register<IModelCreationInjection>( new ModelCreationBuilder() );
```

If I don't do this before using the factory, I get a "KeyNotFoundException"

Is this step really necessary or am I missing something?. If it is, maybe you should add that to the documentation at the front page.

**Comment by OlegAxenow** [comment]
Thank you! Fixed.
